[tool.poetry]
name = "sahibinden-bot"
version = "0.1.0"
description = ""
authors = ["Vyazovetskov Vladimir <erhosen@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.11.1"
aiogram = "^2.20"
httpx = "^0.22.0"
pydantic = {extras = ["dotenv"], version = "^1.9.1"}
urllib3 = "1.25.11"
fake-headers = "^1.0.2"
sentry-sdk = "^1.5.12"
s3-objects-tracker = "^0.3.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
